import {
  groupLines,
  timelineLayout,
  timelineWords,
  type Clip,
  type Overlay,
  type Project,
} from "@powereditor/composition";

/** A clip as the timeline draws it. Removed clips have no length on the timeline; they sit at
 * the cut where they were dropped (the start of the next kept clip). */
export interface TimelineClip {
  clipId: string;
  sourceId: string;
  startFrame: number;
  durationInFrames: number;
  color: string;
  /** Takes recorded for this phrase (the clip plus its alternatives); 0 without alternatives. */
  takes: number;
  lowConfidence: boolean;
  removed: boolean;
}

export interface TimelineOverlay {
  id: string;
  startFrame: number;
  endFrame: number;
  templateId: Overlay["templateId"];
  autoGenerated: boolean;
  /** Row of the Graphics track; overlapping overlays sit on different lanes. */
  lane: number;
}

interface FrameSpan {
  startFrame: number;
  endFrame: number;
}

export interface LegendEntry {
  sourceId: string;
  color: string;
  label: string;
  /** Seconds of the final video taken from this file. */
  seconds: number;
}

export interface TimelineModel {
  fps: number;
  durationInFrames: number;
  video: TimelineClip[];
  removed: TimelineClip[];
  subtitles: { startFrame: number; endFrame: number; text: string }[];
  /** Ordered by lane, then by start: the order the blocks are drawn and tabbed through. */
  graphics: TimelineOverlay[];
  /** Lanes the Graphics track needs (at least one). */
  graphicsLanes: number;
  music: { id: string; label: string }[];
  legend: LegendEntry[];
}

/**
 * The lane of each span, in input order: greedy interval packing by start time, each span
 * taking the first lane whose last span has ended by its start. Ties keep the input order.
 */
export function assignLanes(spans: readonly FrameSpan[]): number[] {
  const byStart = spans
    .map((span, index) => ({ span, index }))
    .sort((a, b) => a.span.startFrame - b.span.startFrame);
  const laneEnds: number[] = [];
  const lanes = spans.map(() => 0);
  for (const { span, index } of byStart) {
    const free = laneEnds.findIndex((end) => end <= span.startFrame);
    const lane = free < 0 ? laneEnds.length : free;
    laneEnds[lane] = span.endFrame;
    lanes[index] = lane;
  }
  return lanes;
}

/** The part of a span the timeline can draw; `continues` when it runs past the end. */
export function visibleSpan(
  span: FrameSpan,
  totalFrames: number,
): FrameSpan & { continues: boolean } {
  return {
    startFrame: Math.min(span.startFrame, totalFrames),
    endFrame: Math.min(span.endFrame, totalFrames),
    continues: span.endFrame > totalFrames,
  };
}

export function fileLabel(path: string): string {
  return path.split(/[\\/]/).pop() ?? path;
}

/** Everything the read-only timeline shows; positions come from the composition's
 * `timelineLayout`, the same layout the Player and the render use. */
export function buildTimeline(project: Project, minConfidence: number): TimelineModel {
  const layout = timelineLayout(project);
  const placements = new Map(layout.clips.map((placement) => [placement.clipId, placement]));
  const colors = new Map(project.sources.map((source) => [source.id, source.displayColor]));
  const view = (clip: Clip, startFrame: number, durationInFrames: number): TimelineClip => ({
    clipId: clip.id,
    sourceId: clip.sourceId,
    startFrame,
    durationInFrames,
    color: colors.get(clip.sourceId) ?? "#808080",
    takes: clip.alternativeTakeIds.length > 0 ? clip.alternativeTakeIds.length + 1 : 0,
    lowConfidence: clip.decisionConfidence != null && clip.decisionConfidence < minConfidence,
    removed: clip.removed,
  });

  const video: TimelineClip[] = [];
  const removed: TimelineClip[] = [];
  const pending: Clip[] = [];
  for (const clip of project.clips) {
    const placement = placements.get(clip.id);
    if (!placement) {
      pending.push(clip);
      continue;
    }
    removed.push(...pending.splice(0).map((gone) => view(gone, placement.startFrame, 0)));
    video.push(view(clip, placement.startFrame, placement.durationInFrames));
  }
  removed.push(...pending.map((gone) => view(gone, layout.durationInFrames, 0)));

  const legend = project.sources.map((source) => {
    const frames = video
      .filter((clip) => clip.sourceId === source.id)
      .reduce((sum, clip) => sum + clip.durationInFrames, 0);
    return {
      sourceId: source.id,
      color: source.displayColor,
      label: fileLabel(source.originalPath),
      seconds: frames / project.fps,
    };
  });

  const lines = groupLines(timelineWords(project), {
    maxWordsPerLine: project.subtitles.style.maxWordsPerLine,
    fps: project.fps,
    durationInFrames: layout.durationInFrames,
  });

  const lanes = assignLanes(project.overlays);
  const graphics = project.overlays
    .map(({ id, startFrame, endFrame, templateId, autoGenerated }, index) => ({
      id,
      startFrame,
      endFrame,
      templateId,
      autoGenerated,
      lane: lanes[index] ?? 0,
    }))
    .sort((a, b) => a.lane - b.lane || a.startFrame - b.startFrame);

  return {
    fps: project.fps,
    durationInFrames: layout.durationInFrames,
    video,
    removed,
    subtitles: lines.map(({ startFrame, endFrame, text }) => ({ startFrame, endFrame, text })),
    graphics,
    graphicsLanes: Math.max(1, ...lanes.map((lane) => lane + 1)),
    music: project.audioTracks
      .filter((track) => track.kind !== "voice")
      .map((track) => ({ id: track.id, label: fileLabel(track.sourcePath ?? track.id) })),
    legend,
  };
}

/** The frame under a horizontal position given as a 0–1 share of the timeline width. */
export function frameAtRatio(ratio: number, durationInFrames: number): number {
  const last = Math.max(0, durationInFrames - 1);
  return Math.min(last, Math.max(0, Math.floor(ratio * durationInFrames)));
}

export function clipAt(model: TimelineModel, frame: number): TimelineClip | undefined {
  return model.video.find(
    (clip) => clip.startFrame <= frame && frame < clip.startFrame + clip.durationInFrames,
  );
}

/** The kept clip `step` places from the selection. A removed clip sits at the cut before the
 * kept clip that starts at its frame; with nothing selected the walk starts at either end. */
export function neighbourClip(
  model: TimelineModel,
  selectedId: string | null,
  step: -1 | 1,
): TimelineClip | undefined {
  const kept = model.video;
  const at = kept.findIndex((clip) => clip.clipId === selectedId);
  if (at >= 0) return kept[at + step];
  const removed = model.removed.find((clip) => clip.clipId === selectedId);
  if (!removed) return step > 0 ? kept[0] : kept.at(-1);
  const after = kept.findIndex((clip) => clip.startFrame >= removed.startFrame);
  if (step > 0) return after < 0 ? undefined : kept[after];
  return kept[(after < 0 ? kept.length : after) - 1];
}

/** Each zoom step (button, key) multiplies or divides the zoom by this. */
export const ZOOM_STEP = 1.5;
/** The deepest zoom: one second at this many pixels... */
const MAX_PX_PER_SECOND = 200;
/** ...but never more than this many times the fitted width, so long videos stay drawable. */
const MAX_ZOOM = 64;
/** Line-based wheel deltas (Firefox) count as this many pixels. */
const WHEEL_LINE_PX = 16;
/** A wheel delta of this many pixels zooms by one step. */
const WHEEL_STEP_PX = 100;
/** Ruler intervals, in seconds, from the finest. */
const RULER_INTERVALS = [0.5, 1, 2, 5, 10, 15, 30, 60, 120, 300, 600];
/** The closest two ruler labels may sit, in pixels. */
const MIN_LABEL_PX = 75;

/** A zoom of 1 fits the whole video in the lane; `max` comes from `maxZoom`. */
export function clampZoom(zoom: number, max: number): number {
  return Math.min(Math.max(zoom, 1), Math.max(max, 1));
}

/** The zoom one step in (`1`) or out (`-1`) from `zoom`. */
export function zoomStep(zoom: number, direction: -1 | 1, max: number): number {
  return clampZoom(direction > 0 ? zoom * ZOOM_STEP : zoom / ZOOM_STEP, max);
}

/** The deepest useful zoom for a video `durationSec` long on a lane `laneWidth` pixels wide when
 * fitted: one second at 200 px, capped at 64x; an unmeasured lane gets the cap. */
export function maxZoom(durationSec: number, laneWidth: number): number {
  if (laneWidth <= 0) return MAX_ZOOM;
  return clampZoom((MAX_PX_PER_SECOND * durationSec) / laneWidth, MAX_ZOOM);
}

/** The scroll position that keeps the point `anchor` pixels into the lane under the same spot of
 * the view after the zoom is multiplied by `ratio`. */
export function zoomedScrollLeft(scrollLeft: number, anchor: number, ratio: number): number {
  return scrollLeft + anchor * (ratio - 1);
}

/** A wheel delta in pixels, whether the browser reports pixels or lines. */
export function wheelPixels(delta: number, deltaMode: number): number {
  return deltaMode === 1 ? delta * WHEEL_LINE_PX : delta;
}

/** The zoom ratio for a Ctrl+wheel or trackpad pinch delta: one mouse notch is one step. */
export function wheelZoomRatio(deltaY: number, deltaMode: number): number {
  return ZOOM_STEP ** (-wheelPixels(deltaY, deltaMode) / WHEEL_STEP_PX);
}

/** Where to scroll so a playhead `playheadX` pixels into the lane is visible again: it lands on
 * the left edge, a page at a time like Premiere. `null` while it is already in view. */
export function followScrollLeft(
  scrollLeft: number,
  viewWidth: number,
  playheadX: number,
): number | null {
  if (playheadX >= scrollLeft && playheadX <= scrollLeft + viewWidth) return null;
  return playheadX;
}

/** The shortest ruler interval, in seconds, whose labels are at least 75 px apart. */
export function rulerInterval(pxPerSecond: number): number {
  return (
    RULER_INTERVALS.find((interval) => interval * pxPerSecond >= MIN_LABEL_PX) ??
    Math.max(...RULER_INTERVALS)
  );
}

function rulerLabel(seconds: number, fractional: boolean): string {
  const minutes = Math.floor(seconds / 60);
  const rest = seconds - minutes * 60;
  return fractional
    ? `${minutes}:${rest.toFixed(1).padStart(4, "0")}`
    : `${minutes}:${String(Math.round(rest)).padStart(2, "0")}`;
}

/** Labelled ruler ticks every `intervalSec`, as frames from the start of the timeline. */
export function rulerTicks(
  durationInFrames: number,
  fps: number,
  intervalSec: number,
): { frame: number; label: string }[] {
  const fractional = !Number.isInteger(intervalSec);
  const ticks = [{ frame: 0, label: rulerLabel(0, fractional) }];
  if (intervalSec * fps <= 0) return ticks;
  for (let index = 1; ; index += 1) {
    const seconds = index * intervalSec;
    const frame = Math.round(seconds * fps);
    if (frame >= durationInFrames) return ticks;
    ticks.push({ frame, label: rulerLabel(seconds, fractional) });
  }
}
