import {
  normalizeOverlayProps,
  timelineLayout,
  type Overlay,
  type OverlayTemplateId,
  type Project,
} from "@powereditor/composition";

/**
 * Pure overlay edits (see `operations.ts` for the conventions). Overlays sit on top of the
 * clips and never change the timeline length: spans are whole frames clamped to the timeline,
 * and an edit that changes nothing returns the same project.
 */

/** Length of a new overlay. */
export const DEFAULT_OVERLAY_SECONDS = 3;
const MIN_OVERLAY_SECONDS = 0.2;

export const minOverlayFrames = (fps: number) => Math.max(1, Math.round(fps * MIN_OVERLAY_SECONDS));

export interface Span {
  startFrame: number;
  endFrame: number;
}

export type DragMode = "move" | "start" | "end";

const clamp = (value: number, low: number, high: number) => Math.min(high, Math.max(low, value));

/**
 * `span` after dragging by `deltaFrames`: "move" shifts it whole (shortened to the timeline if
 * it is longer), "start" and "end" move one edge and keep at least `minFrames`.
 */
export function dragSpan(
  span: Span,
  mode: DragMode,
  deltaFrames: number,
  totalFrames: number,
  minFrames: number,
): Span {
  const delta = Math.round(deltaFrames);
  if (mode === "move") {
    const length = Math.min(span.endFrame - span.startFrame, totalFrames);
    const startFrame = clamp(span.startFrame + delta, 0, totalFrames - length);
    return { startFrame, endFrame: startFrame + length };
  }
  if (mode === "start") {
    const latest = Math.max(0, span.endFrame - minFrames);
    return { startFrame: clamp(span.startFrame + delta, 0, latest), endFrame: span.endFrame };
  }
  const earliest = Math.min(totalFrames, span.startFrame + minFrames);
  return {
    startFrame: span.startFrame,
    endFrame: clamp(span.endFrame + delta, earliest, totalFrames),
  };
}

/** Whole frames that a horizontal pointer move of `pixels` covers on a lane `laneWidth` wide. */
export function framesForPixels(pixels: number, laneWidth: number, totalFrames: number): number {
  if (laneWidth <= 0) return 0;
  return Math.round((pixels / laneWidth) * totalFrames) || 0;
}

function updateOverlay(
  project: Project,
  id: string,
  change: (overlay: Overlay) => Overlay,
): Project {
  let changed = false;
  const overlays = project.overlays.map((overlay) => {
    if (overlay.id !== id) return overlay;
    const next = change(overlay);
    if (next === overlay) return overlay;
    changed = true;
    return next;
  });
  return changed ? { ...project, overlays } : project;
}

const totalFrames = (project: Project) => timelineLayout(project).durationInFrames;

/** The project's accent: new graphics take the subtitle highlight color. */
export const projectAccent = (project: Project) => project.subtitles.style.highlightColor;

/** A new overlay at `atFrame`, moved back when its default length would pass the end. Its props
 * are the template's defaults with `props` applied over them. */
export function addOverlay(
  project: Project,
  {
    id,
    templateId,
    atFrame,
    props,
  }: { id: string; templateId: OverlayTemplateId; atFrame: number; props: Record<string, unknown> },
): Project {
  const total = totalFrames(project);
  if (total === 0) return project;
  const length = Math.min(Math.round(DEFAULT_OVERLAY_SECONDS * project.fps), total);
  const startFrame = clamp(Math.round(atFrame), 0, total - length);
  const added: Overlay = {
    id,
    templateId,
    startFrame,
    endFrame: startFrame + length,
    props: { ...normalizeOverlayProps(templateId, props, projectAccent(project)) },
    autoGenerated: false,
  };
  return { ...project, overlays: [...project.overlays, added] };
}

export function setOverlayProps(
  project: Project,
  id: string,
  changes: Record<string, unknown>,
): Project {
  return updateOverlay(project, id, (overlay) => {
    const same = Object.entries(changes).every(([key, value]) => overlay.props[key] === value);
    return same ? overlay : { ...overlay, props: { ...overlay.props, ...changes } };
  });
}

export function removeOverlay(project: Project, id: string): Project {
  const overlays = project.overlays.filter((overlay) => overlay.id !== id);
  return overlays.length === project.overlays.length ? project : { ...project, overlays };
}

function withSpan(overlay: Overlay, span: Span): Overlay {
  return span.startFrame === overlay.startFrame && span.endFrame === overlay.endFrame
    ? overlay
    : { ...overlay, ...span };
}

/** Place an overlay at whole frames inside the timeline, at least the minimum length long. */
export function setOverlaySpan(
  project: Project,
  id: string,
  startFrame: number,
  endFrame: number,
): Project {
  const total = totalFrames(project);
  const minimum = Math.min(minOverlayFrames(project.fps), total);
  return updateOverlay(project, id, (overlay) => {
    const start = clamp(Math.round(startFrame), 0, Math.max(0, total - minimum));
    const end = clamp(Math.round(endFrame), start + minimum, total);
    return withSpan(overlay, { startFrame: start, endFrame: end });
  });
}

/** Shift an overlay by `deltaFrames` (keyboard nudges and drops of a drag). */
export function moveOverlay(project: Project, id: string, deltaFrames: number): Project {
  const total = totalFrames(project);
  return updateOverlay(project, id, (overlay) =>
    withSpan(overlay, dragSpan(overlay, "move", deltaFrames, total, minOverlayFrames(project.fps))),
  );
}
