import json
from pathlib import Path
from typing import Any

import pytest
from pydantic import ValidationError

from autocut.models import Clip, Project, Transcript, Word, load_project, save_project


def _clip_payload(**overrides: Any) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "id": "c1",
        "sourceId": "s1",
        "inSec": 1.0,
        "outSec": 2.5,
        "speed": 1.0,
        "volume": 1.0,
        "transitionIn": {"type": "punch_in", "durationFrames": 0},
        "alternativeTakeIds": [],
        "removed": False,
    }
    payload.update(overrides)
    return payload


def _project_payload() -> dict[str, Any]:
    return {
        "version": 1,
        "preset": "reel_9x16",
        "fps": 30,
        "sources": [
            {
                "id": "s1",
                "originalPath": "C:/videos/toma ñ.mp4",
                "mezzaninePath": "m.mp4",
                "proxyPath": "p.mp4",
                "displayColor": "#ff0000",
                "loudnessLufs": -18.5,
                "colorStats": {"meanLuma": 0.5, "meanR": 0.4, "meanG": 0.5, "meanB": 0.6},
            }
        ],
        "clips": [_clip_payload(colorOverride={"brightness": 0.1})],
        "audioTracks": [{"id": "a1", "kind": "voice", "volume": 1.0, "duckingEnabled": False}],
        "subtitles": {
            "style": {
                "preset": "karaoke_highlight",
                "fontSize": 64,
                "position": "bottom",
                "highlightColor": "#ffff00",
                "maxWordsPerLine": 3,
            },
            "words": [{"text": "hola", "startFrame": 0, "endFrame": 10, "clipId": "c1"}],
        },
        "overlays": [
            {
                "id": "o1",
                "templateId": "cta",
                "startFrame": 0,
                "endFrame": 30,
                "props": {"text": "Follow"},
                "autoGenerated": True,
            }
        ],
        "colorGrade": {
            "preset": "natural",
            "brightness": 0.0,
            "contrast": 1.0,
            "saturation": 1.0,
            "temperature": 0.0,
        },
    }


def test_project_round_trips_with_camel_case_keys() -> None:
    payload = _project_payload()

    project = Project.model_validate(payload)

    assert project.clips[0].source_id == "s1"
    assert project.clips[0].color_override is not None
    assert project.clips[0].color_override.brightness == 0.1
    assert project.clips[0].color_override.contrast is None
    dumped = project.model_dump(by_alias=True, mode="json", exclude_none=True)
    assert dumped == payload


def test_models_accept_python_field_names() -> None:
    clip = Clip.model_validate(
        {k: v for k, v in _clip_payload().items() if k not in {"sourceId", "inSec"}}
        | {"source_id": "s9", "in_sec": 0.0}
    )

    assert clip.source_id == "s9"
    assert clip.in_sec == 0.0


@pytest.mark.parametrize(
    "overrides",
    [
        {"speed": 0.4},
        {"speed": 2.1},
        {"volume": -0.1},
        {"volume": 2.5},
        {"transitionIn": {"type": "wipe", "durationFrames": 0}},
        {"unknownField": 1},
    ],
)
def test_clip_rejects_invalid_values(overrides: dict[str, Any]) -> None:
    with pytest.raises(ValidationError):
        Clip.model_validate(_clip_payload(**overrides))


def test_clip_accepts_range_bounds() -> None:
    clip = Clip.model_validate(_clip_payload(speed=2.0, volume=0.0))

    assert (clip.speed, clip.volume) == (2.0, 0.0)


def test_project_rejects_unknown_version() -> None:
    payload = _project_payload() | {"version": 2}

    with pytest.raises(ValidationError):
        Project.model_validate(payload)


def test_save_and_load_project_round_trip(tmp_path: Path) -> None:
    project = Project.model_validate(_project_payload())
    target = tmp_path / "nested" / "project.json"

    save_project(project, target)

    assert load_project(target) == project
    on_disk = json.loads(target.read_text(encoding="utf-8"))
    assert on_disk["audioTracks"][0]["duckingEnabled"] is False
    assert [p.name for p in target.parent.iterdir()] == ["project.json"]


def test_save_project_replaces_existing_file(tmp_path: Path) -> None:
    target = tmp_path / "project.json"
    target.write_text("stale", encoding="utf-8")
    project = Project.model_validate(_project_payload())

    save_project(project, target)

    assert load_project(target).fps == 30


def test_transcript_word_probability_is_optional() -> None:
    transcript = Transcript.model_validate(
        {
            "language": "es",
            "provider": "openai",
            "model": "whisper-1",
            "words": [{"text": "hola", "start": 0.0, "end": 0.4}],
        }
    )

    assert transcript.words == [Word(text="hola", start=0.0, end=0.4, prob=None)]
