/* eslint-disable */
// Generated from schema/project.schema.json by `corepack pnpm gen:types`. Do not edit.
// Regenerate the schema with `uv run python -m powereditor.schema_gen` in backend/.

export interface Project {
  audioTracks: AudioTrack[];
  clips: Clip[];
  colorGrade: ColorGrade;
  fps: number;
  overlays: Overlay[];
  preset: "reel_9x16" | "landscape_16x9";
  sources: Source[];
  subtitles: Subtitles;
  version: 1;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "AudioTrack".
 */
export interface AudioTrack {
  duckingEnabled: boolean;
  id: string;
  kind: "voice" | "music" | "sfx";
  sourcePath?: string | null;
  volume: number;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "Clip".
 */
export interface Clip {
  alternativeTakeIds: string[];
  colorOverride?: ColorGradeOverride | null;
  decisionConfidence?: number | null;
  id: string;
  inSec: number;
  outSec: number;
  removed: boolean;
  sourceId: string;
  speed: number;
  takeGroupId?: string | null;
  transitionIn: TransitionIn;
  volume: number;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "ColorGradeOverride".
 */
export interface ColorGradeOverride {
  brightness?: number | null;
  contrast?: number | null;
  preset?: ("natural" | "warm" | "cool" | "bw") | null;
  saturation?: number | null;
  temperature?: number | null;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "TransitionIn".
 */
export interface TransitionIn {
  durationFrames: number;
  type: "cut" | "punch_in" | "fade" | "slide";
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "ColorGrade".
 */
export interface ColorGrade {
  brightness: number;
  contrast: number;
  preset: "natural" | "warm" | "cool" | "bw";
  saturation: number;
  temperature: number;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "Overlay".
 */
export interface Overlay {
  autoGenerated: boolean;
  endFrame: number;
  id: string;
  props: {
    [k: string]: unknown;
  };
  startFrame: number;
  templateId: "title" | "lower_third" | "cta" | "logo" | "progress_bar" | "image";
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "Source".
 */
export interface Source {
  colorStats: ColorStats;
  displayColor: string;
  id: string;
  loudnessLufs: number;
  mezzaninePath: string;
  originalPath: string;
  proxyPath: string;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "ColorStats".
 */
export interface ColorStats {
  meanB: number;
  meanG: number;
  meanLuma: number;
  meanR: number;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "Subtitles".
 */
export interface Subtitles {
  style: SubtitleStyle;
  words: TimelineWord[];
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "SubtitleStyle".
 */
export interface SubtitleStyle {
  fontSize: number;
  highlightColor: string;
  maxWordsPerLine: number;
  position: "bottom" | "center" | "top";
  preset: "karaoke_highlight" | "clean" | "bold_pop" | "minimal";
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "TimelineWord".
 */
export interface TimelineWord {
  clipId: string;
  endFrame: number;
  startFrame: number;
  text: string;
}
