// Mirrors the backend Project schema. To be generated from the Pydantic JSON Schema later.

export interface Project {
  version: 1;
  preset: "reel_9x16" | "landscape_16x9";
  fps: number;
  sources: Source[];
  clips: Clip[];
  audioTracks: AudioTrack[];
  subtitles: { style: SubtitleStyle; words: TimelineWord[] };
  overlays: Overlay[];
  colorGrade: ColorGrade;
}

export interface Source {
  id: string;
  originalPath: string;
  mezzaninePath: string;
  proxyPath: string;
  displayColor: string;
  loudnessLufs: number;
  colorStats: { meanLuma: number; meanR: number; meanG: number; meanB: number };
}

export type TransitionType = "cut" | "punch_in" | "fade" | "slide";

export interface Clip {
  id: string;
  sourceId: string;
  inSec: number;
  outSec: number;
  speed: number;
  volume: number;
  transitionIn: { type: TransitionType; durationFrames: number };
  takeGroupId?: string;
  alternativeTakeIds: string[];
  decisionConfidence?: number;
  colorOverride?: Partial<ColorGrade>;
  removed: boolean;
}

export interface AudioTrack {
  id: string;
  kind: "voice" | "music" | "sfx";
  sourcePath?: string;
  volume: number;
  duckingEnabled: boolean;
}

export interface TimelineWord {
  text: string;
  startFrame: number;
  endFrame: number;
  clipId: string;
}

export interface SubtitleStyle {
  preset: "karaoke_highlight" | "clean" | "bold_pop" | "minimal";
  fontSize: number;
  position: "bottom" | "center" | "top";
  highlightColor: string;
  maxWordsPerLine: number;
}

export interface Overlay {
  id: string;
  templateId: "title" | "lower_third" | "cta" | "logo" | "progress_bar" | "image";
  startFrame: number;
  endFrame: number;
  props: Record<string, unknown>;
  autoGenerated: boolean;
}

export interface ColorGrade {
  preset: "natural" | "warm" | "cool" | "bw";
  brightness: number;
  contrast: number;
  saturation: number;
  temperature: number;
}
