import type { Project } from "@powereditor/composition";

const clip = (id: string, sourceId: string, inSec: number, outSec: number, extra = {}) => ({
  id,
  sourceId,
  inSec,
  outSec,
  speed: 1,
  volume: 1,
  transitionIn: { type: "cut" as const, durationFrames: 0 },
  alternativeTakeIds: [],
  removed: false,
  ...extra,
});
const source = (id: string, displayColor: string, originalPath: string) => ({
  id,
  displayColor,
  originalPath,
  mezzaninePath: `${id}.mezzanine.mp4`,
  proxyPath: `${id}.proxy.mp4`,
  loudnessLufs: -16,
  colorStats: { meanLuma: 0.5, meanR: 0.5, meanG: 0.5, meanB: 0.5 },
});

/** Two sources, a take group with a low-confidence pick, removed clips, a line, a title and music. */
export const PROJECT: Project = {
  version: 1,
  preset: "reel_9x16",
  fps: 30,
  sources: [
    source("a", "#111111", "C:/rec/cam-a.mp4"),
    source("b", "#222222", "D:\\rec\\cam-b.MOV"),
  ],
  clips: [
    clip("k1", "a", 0, 2, {
      alternativeTakeIds: ["r1"],
      takeGroupId: "g1",
      decisionConfidence: 0.5,
    }),
    clip("r1", "a", 2, 4, { removed: true, takeGroupId: "g1" }),
    clip("k2", "b", 0, 1, { decisionConfidence: 0.95 }),
    clip("r2", "b", 1, 2, { removed: true }),
    clip("k3", "a", 5, 6, { speed: 2 }),
  ],
  audioTracks: [
    { id: "voice", kind: "voice", volume: 1, duckingEnabled: false },
    { id: "m1", kind: "music", sourcePath: "C:/music/song.mp3", volume: 0.3, duckingEnabled: true },
  ],
  subtitles: {
    style: {
      preset: "clean",
      fontSize: 60,
      position: "bottom",
      highlightColor: "#ffcc00",
      maxWordsPerLine: 3,
    },
    words: [
      { text: "Hola", startFrame: 0, endFrame: 10, clipId: "k1" },
      { text: "mundo.", startFrame: 12, endFrame: 20, clipId: "k1" },
    ],
  },
  overlays: [
    { id: "o1", templateId: "title", startFrame: 0, endFrame: 30, props: {}, autoGenerated: true },
  ],
  colorGrade: { preset: "natural", brightness: 0, contrast: 0, saturation: 0, temperature: 0 },
};
