import { describe, expect, it } from "vitest";

import { readableTextColor } from "../src/overlays/color";
import { overlayInsets, overlayUnit } from "../src/overlays/layout";
import { overlayMotion } from "../src/overlays/motion";
import { overlaySpans } from "../src/overlays/spans";
import {
  defaultOverlayProps,
  normalizeOverlayProps,
  OVERLAY_FIELDS,
  OVERLAY_TEMPLATES,
} from "../src/overlays/templates";
import type { Overlay, Project } from "../src/types";
import fixture from "./fixtures/project.json";

const ACCENT = "#FFD400";
const project = fixture.project as Project;

const overlay = (id: string, startFrame: number, endFrame: number): Overlay => ({
  id,
  templateId: "title",
  startFrame,
  endFrame,
  props: {},
  autoGenerated: false,
});

describe("overlay props", () => {
  it("fills every template's defaults, with the project accent as the color", () => {
    expect(defaultOverlayProps("title", ACCENT)).toEqual({
      text: "",
      subtitle: "",
      position: "center",
      color: ACCENT,
    });
    expect(defaultOverlayProps("logo", ACCENT)).toEqual({
      src: "",
      corner: "top_right",
      size: 0.14,
      opacity: 0.9,
    });
    expect(defaultOverlayProps("progress_bar", ACCENT)).toEqual({
      position: "top",
      color: ACCENT,
      thickness: 10,
    });
  });

  it("keeps valid values and replaces invalid ones with defaults", () => {
    const props = normalizeOverlayProps(
      "lower_third",
      { name: "  Ana Pérez ", role: 42, side: "middle", color: "#00aa11", extra: true },
      ACCENT,
    );
    expect(props).toEqual({ name: "Ana Pérez", role: "", side: "left", color: "#00aa11" });
  });

  it("refuses colors that are not six-digit hex", () => {
    const props = normalizeOverlayProps("cta", { text: "Sígueme", color: "red" }, ACCENT);
    expect(props.color).toBe(ACCENT);
    expect(props.text).toBe("Sígueme");
  });

  it("clamps numbers into their range and drops non-finite ones", () => {
    expect(normalizeOverlayProps("image", { size: 5 }, ACCENT).size).toBe(1);
    expect(normalizeOverlayProps("image", { size: Number.NaN }, ACCENT).size).toBe(0.6);
    expect(normalizeOverlayProps("progress_bar", { thickness: 1 }, ACCENT).thickness).toBe(4);
  });

  it("keeps only the file name of an image, so it is always served from the media folder", () => {
    expect(normalizeOverlayProps("image", { src: "C:\\x\\..\\overlay-1.png" }, ACCENT).src).toBe(
      "overlay-1.png",
    );
    expect(normalizeOverlayProps("logo", { src: "../.." }, ACCENT).src).toBe("");
  });

  it("describes a form field for every default prop of every template", () => {
    expect(OVERLAY_TEMPLATES).toHaveLength(6);
    for (const templateId of OVERLAY_TEMPLATES) {
      const keys = OVERLAY_FIELDS[templateId].map((field) => field.key).sort();
      expect(keys).toEqual(Object.keys(defaultOverlayProps(templateId, ACCENT)).sort());
    }
  });
});

describe("overlay layout", () => {
  const reel = { ...project, preset: "reel_9x16" as const };
  const landscape = { ...project, preset: "landscape_16x9" as const };
  const withSubtitles = (base: Project, position: "top" | "center" | "bottom"): Project => ({
    ...base,
    subtitles: { ...base.subtitles, style: { ...base.subtitles.style, position, fontSize: 60 } },
  });

  it("keeps graphics inside the preset's safe area", () => {
    expect(overlayInsets(withSubtitles(reel, "center"), 1080, 1920)).toEqual({
      top: 230,
      bottom: 461,
      left: 65,
      right: 173,
    });
    expect(overlayInsets(withSubtitles(landscape, "center"), 1920, 1080)).toEqual({
      top: 86,
      bottom: 108,
      left: 115,
      right: 115,
    });
  });

  it("lifts bottom graphics above bottom subtitles and lowers top graphics under top ones", () => {
    // Two lines at 1.2 line height plus half a line of gap: 60 * 2.9 = 174 px.
    expect(overlayInsets(withSubtitles(reel, "bottom"), 1080, 1920).bottom).toBe(461 + 174);
    expect(overlayInsets(withSubtitles(reel, "top"), 1080, 1920).top).toBe(230 + 174);
    expect(overlayInsets(withSubtitles(reel, "top"), 1080, 1920).bottom).toBe(461);
  });

  it("scales sizes with the short side of the frame", () => {
    expect(overlayUnit(1080, 1920)).toBe(1);
    expect(overlayUnit(1280, 720)).toBeCloseTo(720 / 1080);
  });
});

describe("overlay motion", () => {
  const FPS = 30;

  it("enters over 0.4 s, holds, and leaves over the last 0.3 s", () => {
    expect(overlayMotion(0, 90, FPS)).toBe(0);
    expect(overlayMotion(6, 90, FPS)).toBeGreaterThan(0.5);
    expect(overlayMotion(6, 90, FPS)).toBeLessThan(1);
    expect(overlayMotion(12, 90, FPS)).toBeCloseTo(1, 2);
    expect(overlayMotion(45, 90, FPS)).toBe(1);
    expect(overlayMotion(81, 90, FPS)).toBe(1);
    expect(overlayMotion(85, 90, FPS)).toBeLessThan(1);
    // The exit accelerates: most of the fall happens in its last frames.
    expect(overlayMotion(88, 90, FPS)).toBeLessThan(overlayMotion(85, 90, FPS) - 0.3);
    expect(overlayMotion(90, 90, FPS)).toBe(0);
  });

  it("shares a short overlay between its entrance and its exit", () => {
    expect(overlayMotion(0, 10, FPS)).toBe(0);
    expect(overlayMotion(5, 10, FPS)).toBeCloseTo(1, 2);
    expect(overlayMotion(9, 10, FPS)).toBeLessThan(0.5);
  });
});

describe("overlaySpans", () => {
  it("clamps overlays to the timeline and drops the ones with nothing to show", () => {
    const spans = overlaySpans(
      [overlay("a", 10, 40), overlay("b", 80, 150), overlay("c", 100, 120), overlay("d", 5, 5)],
      100,
    );
    expect(
      spans.map(({ overlay: { id }, from, durationInFrames }) => [id, from, durationInFrames]),
    ).toEqual([
      ["a", 10, 30],
      ["b", 80, 20],
    ]);
  });

  it("never lets a reversed overlay reach the composition", () => {
    expect(overlaySpans([overlay("r", 50, 20)], 100)).toEqual([]);
  });
});

describe("readableTextColor", () => {
  it("puts dark text on light accents and white text on dark ones", () => {
    expect(readableTextColor("#FFD400")).toBe("#111111");
    expect(readableTextColor("#0072B2")).toBe("#FFFFFF");
    expect(readableTextColor("#000000")).toBe("#FFFFFF");
  });
});
