import { timelineLayout, type Overlay, type Project } from "@powereditor/composition";
import { describe, expect, it } from "vitest";
import {
  addOverlay,
  dragSpan,
  framesForPixels,
  minOverlayFrames,
  moveOverlay,
  removeOverlay,
  setOverlayProps,
  setOverlaySpan,
} from "../src/edit/overlays";
import { PROJECT } from "./fixtures/reviewProject";

// Kept clips: 2 s + 1 s + 0.5 s (speed 2) at 30 fps.
const TOTAL = timelineLayout(PROJECT).durationInFrames;
const overlay = (project: Project, id: string): Overlay | undefined =>
  project.overlays.find((candidate) => candidate.id === id);

describe("overlay edits", () => {
  it("adds an overlay at the playhead with its default length and props", () => {
    const next = addOverlay(PROJECT, {
      id: "o2",
      templateId: "cta",
      atFrame: 15,
      props: { text: "Sígueme" },
    });

    expect(TOTAL).toBe(105);
    expect(overlay(next, "o2")).toEqual({
      id: "o2",
      templateId: "cta",
      startFrame: 15,
      endFrame: 105,
      props: { text: "Sígueme", position: "bottom", color: "#ffcc00" },
      autoGenerated: false,
    });
    expect(next.clips).toBe(PROJECT.clips);
  });

  it("moves a new overlay back so it fits before the end of the timeline", () => {
    const next = addOverlay(PROJECT, { id: "o2", templateId: "title", atFrame: 100, props: {} });
    expect(overlay(next, "o2")).toMatchObject({ startFrame: 15, endFrame: 105 });
  });

  it("adds nothing to an empty timeline", () => {
    const empty = { ...PROJECT, clips: [] };
    expect(addOverlay(empty, { id: "o2", templateId: "title", atFrame: 0, props: {} })).toBe(empty);
  });

  it("merges prop changes and keeps the auto-generated mark", () => {
    const next = setOverlayProps(PROJECT, "o1", { text: "Hola" });
    expect(overlay(next, "o1")).toMatchObject({ props: { text: "Hola" }, autoGenerated: true });
    expect(setOverlayProps(next, "o1", { text: "Hola" })).toBe(next);
  });

  it("removes an overlay and ignores unknown ids", () => {
    expect(removeOverlay(PROJECT, "o1").overlays).toEqual([]);
    expect(removeOverlay(PROJECT, "nope")).toBe(PROJECT);
  });

  it("snaps spans to whole frames inside the timeline with a minimum length", () => {
    const next = setOverlaySpan(PROJECT, "o1", 10.4, 200);
    expect(overlay(next, "o1")).toMatchObject({ startFrame: 10, endFrame: TOTAL });
    const tiny = setOverlaySpan(PROJECT, "o1", 50, 50);
    expect(overlay(tiny, "o1")).toMatchObject({
      startFrame: 50,
      endFrame: 50 + minOverlayFrames(30),
    });
    expect(setOverlaySpan(PROJECT, "o1", 0, 30)).toBe(PROJECT);
  });

  it("moves an overlay by whole frames and stops at both ends", () => {
    expect(overlay(moveOverlay(PROJECT, "o1", 10), "o1")).toMatchObject({
      startFrame: 10,
      endFrame: 40,
    });
    expect(overlay(moveOverlay(PROJECT, "o1", 500), "o1")).toMatchObject({
      startFrame: 75,
      endFrame: 105,
    });
    expect(moveOverlay(PROJECT, "o1", -5)).toBe(PROJECT);
  });
});

describe("dragSpan", () => {
  const span = { startFrame: 20, endFrame: 50 };

  it("moves the whole span, keeping its length inside the timeline", () => {
    expect(dragSpan(span, "move", 30, 105, 6)).toEqual({ startFrame: 50, endFrame: 80 });
    expect(dragSpan(span, "move", -40, 105, 6)).toEqual({ startFrame: 0, endFrame: 30 });
    expect(dragSpan(span, "move", 90, 105, 6)).toEqual({ startFrame: 75, endFrame: 105 });
  });

  it("resizes one edge without crossing the other", () => {
    expect(dragSpan(span, "start", -5, 105, 6)).toEqual({ startFrame: 15, endFrame: 50 });
    expect(dragSpan(span, "start", 40, 105, 6)).toEqual({ startFrame: 44, endFrame: 50 });
    expect(dragSpan(span, "end", 100, 105, 6)).toEqual({ startFrame: 20, endFrame: 105 });
    expect(dragSpan(span, "end", -40, 105, 6)).toEqual({ startFrame: 20, endFrame: 26 });
  });

  it("shortens an overlay longer than the timeline when it moves", () => {
    expect(dragSpan({ startFrame: 0, endFrame: 300 }, "move", 5, 105, 6)).toEqual({
      startFrame: 0,
      endFrame: 105,
    });
  });
});

describe("framesForPixels", () => {
  it("turns a pointer distance into whole frames of the lane", () => {
    expect(framesForPixels(50, 500, 100)).toBe(10);
    expect(framesForPixels(-26, 500, 100)).toBe(-5);
    expect(framesForPixels(10, 0, 100)).toBe(0);
  });
});
