import { describe, expect, it } from "vitest";
import {
  assignLanes,
  buildTimeline,
  clipAt,
  fileLabel,
  frameAtRatio,
  neighbourClip,
  visibleSpan,
} from "../src/review/timelineModel";
import { PROJECT } from "./fixtures/reviewProject";

describe("buildTimeline", () => {
  const model = buildTimeline(PROJECT, 0.8);

  it("places kept clips back to back in their source color", () => {
    expect(model.durationInFrames).toBe(105);
    expect(model.video.map((c) => [c.clipId, c.startFrame, c.durationInFrames, c.color])).toEqual([
      ["k1", 0, 60, "#111111"],
      ["k2", 60, 30, "#222222"],
      ["k3", 90, 15, "#111111"],
    ]);
  });

  it("badges alternatives and flags low-confidence decisions", () => {
    expect(model.video.map((c) => [c.takes, c.lowConfidence])).toEqual([
      [2, true],
      [0, false],
      [0, false],
    ]);
  });

  it("anchors removed clips at the cut where they were dropped", () => {
    expect(model.removed.map((c) => [c.clipId, c.startFrame, c.removed])).toEqual([
      ["r1", 60, true],
      ["r2", 90, true],
    ]);
  });

  it("lists which file is used for how long, and the other tracks", () => {
    expect(model.legend).toEqual([
      { sourceId: "a", color: "#111111", label: "cam-a.mp4", seconds: 2.5 },
      { sourceId: "b", color: "#222222", label: "cam-b.MOV", seconds: 1 },
    ]);
    expect(model.subtitles).toEqual([{ startFrame: 0, endFrame: 35, text: "Hola mundo." }]);
    expect(model.graphics).toEqual([
      { id: "o1", startFrame: 0, endFrame: 30, templateId: "title", autoGenerated: true, lane: 0 },
    ]);
    expect(model.graphicsLanes).toBe(1);
    expect(model.music).toEqual([{ id: "m1", label: "song.mp3" }]);
  });
});

describe("timeline helpers", () => {
  const model = buildTimeline(PROJECT, 0.8);

  it("maps a click position to a frame inside the timeline", () => {
    expect(frameAtRatio(0.5, 105)).toBe(52);
    expect(frameAtRatio(1.4, 105)).toBe(104);
    expect(frameAtRatio(-1, 105)).toBe(0);
  });

  it("finds the kept clip under a frame", () => {
    expect(clipAt(model, 61)?.clipId).toBe("k2");
    expect(clipAt(model, 105)).toBeUndefined();
    expect(fileLabel("D:\\a\\b.mp4")).toBe("b.mp4");
  });

  it("walks the kept clips from the selection, a removed clip or either end", () => {
    const walk = (id: string | null, step: -1 | 1) => neighbourClip(model, id, step)?.clipId;
    expect([walk("k1", 1), walk("k2", -1), walk("k3", 1)]).toEqual(["k2", "k1", undefined]);
    // r2 was dropped at the cut before k3.
    expect([walk("r2", 1), walk("r2", -1)]).toEqual(["k3", "k2"]);
    expect([walk(null, 1), walk(null, -1)]).toEqual(["k1", "k3"]);
  });
});

describe("graphics lanes", () => {
  const span = (startFrame: number, endFrame: number) => ({ startFrame, endFrame });

  it("keeps back-to-back overlays on one lane", () => {
    expect(assignLanes([span(0, 75), span(75, 150), span(150, 225)])).toEqual([0, 0, 0]);
  });

  it("moves overlapping and contained overlays to the next free lane", () => {
    expect(assignLanes([span(0, 100), span(50, 150), span(60, 70), span(120, 200)])).toEqual([
      0, 1, 2, 0,
    ]);
  });

  it("packs by start time whatever the project order, keeping ties in project order", () => {
    expect(assignLanes([span(75, 150), span(0, 75), span(0, 225)])).toEqual([0, 0, 1]);
    expect(assignLanes([])).toEqual([]);
  });

  it("stacks the five overlays of a typical project on three lanes, in lane order", () => {
    const overlays = [
      ["title", 0, 75],
      ["lower_third", 75, 150],
      ["cta", 150, 225],
      ["progress_bar", 0, 1800],
      ["logo", 0, 225],
    ] as const;
    const graphics = buildTimeline(
      {
        ...PROJECT,
        overlays: overlays.map(([templateId, startFrame, endFrame]) => ({
          id: templateId,
          templateId,
          startFrame,
          endFrame,
          props: {},
          autoGenerated: false,
        })),
      },
      0.8,
    );
    expect(graphics.graphicsLanes).toBe(3);
    expect(graphics.graphics.map(({ id, lane }) => [id, lane])).toEqual([
      ["title", 0],
      ["lower_third", 0],
      ["cta", 0],
      ["progress_bar", 1],
      ["logo", 2],
    ]);
  });

  it("clips an overlay to the end of the timeline and marks that it continues", () => {
    expect(visibleSpan(span(0, 1800), 237)).toEqual({
      startFrame: 0,
      endFrame: 237,
      continues: true,
    });
    expect(visibleSpan(span(150, 225), 237)).toEqual({
      startFrame: 150,
      endFrame: 225,
      continues: false,
    });
    expect(visibleSpan(span(300, 400), 237)).toEqual({
      startFrame: 237,
      endFrame: 237,
      continues: true,
    });
  });
});
